#!/usr/bin/env node
// Derive pi-mmx's skills from the canonical mmx skills in this repository.
//
//   node scripts/derive-skills.mjs          write adapters/pi/skills/
//   node scripts/derive-skills.mjs --check  exit 1 if the committed copies differ
//
// The canonical sources are skills/mmx/SKILL.md (+ references/diff-schema.md)
// and adapters/codemap/SKILL.md (+ its scripts and worked example). The pi
// copies differ only by the ordered rules below. Every rule marked
// `required: true` must match: when the canonical text is rewritten, this
// script fails instead of silently shipping shell instructions that pi's
// tools replace. No dependencies; Node 22 or newer.

import { existsSync, promises as fs } from "node:fs";
import { dirname, join, relative, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const repoRoot = resolve(packageRoot, "..", "..");
const skillsRoot = join(packageRoot, "skills");

const GENERATED = (source) =>
	`<!-- Generated by adapters/pi/scripts/derive-skills.mjs from ${source}. Do not edit by hand: edit the canonical file and run \`npm run derive-skills\` in adapters/pi. -->`;

// Text that must never survive a derivation (checked on every derived file).
export const FORBIDDEN = [
	{ name: "--by agent", pattern: /--by agent/ },
	{ name: "--by human", pattern: /--by human/ },
	{ name: "--print-if-changed", pattern: /--print-if-changed/ },
	{ name: "mmx serve/wait/note/render shell line", pattern: /^\s*mmx (serve|wait|note|render)\b/m },
	{ name: "inline mmx serve command", pattern: /`mmx serve [^`]*`/ },
	{ name: "inline mmx wait command", pattern: /`mmx wait [^`-][^`]*`/ },
	{ name: "inline mmx note command", pattern: /`mmx note [^`-][^`]*`/ },
	{ name: "inline mmx render command with a note", pattern: /`mmx render [^`]*--note[^`]*`/ },
	{ name: "claude.ai", pattern: /claude\.ai/ },
];

const MMX_IN_PI = `## In pi

The pi-mmx extension runs the mmx routine for you:

- Before each run it collects the human's unanswered turns for every tracked
  diagram and injects them as an \`mmx-turn\` message. Read it first.
- \`.mmd\` edits made with pi's \`edit\` and \`write\` tools are validated
  automatically (in a temporary copy; nothing is sent). An edit you leave
  unsent is sent at the end of the run with an automatic note.
- Your job is the note. After editing, call \`mmx_render({path, note})\` with
  what changed and why. To reply without editing, call
  \`mmx_note({path, text})\`. To block for a reply inside a run, call
  \`mmx_wait({path, timeoutSeconds})\`.
- Suggest \`/mmx open <path>\` when the human should see or edit the picture
  in the local cockpit.

The sections below describe the same routine with these tools. The \`mmx\`
shell commands that remain (such as \`mmx doctor\`) run through \`bash\`.
`;

const CODEMAP_IN_PI = `## In pi

The \`mmx\` skill's routine runs through the pi-mmx tools: render with
\`mmx_render({path, note})\`, reply with \`mmx_note({path, text})\`, read the
human's turns from \`mmx-turn\` messages (or \`mmx_wait\`), and suggest
\`/mmx open <path>\` for the cockpit. \`codemap.py\` and the \`example/\` files
are bundled next to this SKILL.md; \`<skill-dir>\` below means that directory.
`;

const MMX_RULES = [
	{
		name: "frontmatter description",
		pattern: /^description: .*$/m,
		replace:
			'description: "Use when a Mermaid .mmd diagram is shared with a human through pi-mmx and the mmx cockpit (/mmx open), including when displaying it: read mmx-turn messages as the human\'s message, call mmx_render with a note after each .mmd edit, reply with mmx_note, fix parse errors, and show only mmx-rendered SVG."',
		required: true,
	},
	{
		name: "in-pi block after the title",
		pattern: /^(# mmx diagram conversation\n)/m,
		replace: `$1\n${MMX_IN_PI}`,
		required: true,
	},
	{
		name: "turn start: injected mmx-turn instead of wait/render --by human",
		pattern: /At the start of \*\*every\*\* turn, collect the human's changes[\s\S]*?Replace `diagram\.mmd` with the project's configured path\./,
		replace:
			"At the start of **every** turn, the extension collects the human's changes for you: before your run it asks mmx for each tracked diagram's unanswered human turns without waiting (without `mmx serve` running, this renders a direct edit of the file as the human's turn) and injects the human's unanswered turns as an `mmx-turn` message before your turn. Read them first. Each turn is injected once per session; `mmx_wait` still shows every unanswered turn.\n\nA diagram is tracked once it is listed in `.pi/mmx.json`, opened with `/mmx open`, used with `mmx_render`, `mmx_note` or `mmx_wait`, or edited with pi's `edit` or `write`. No turn is injected for a diagram while you have an unsent edit to it.",
		required: true,
	},
	{
		name: "agent render command -> mmx_render",
		pattern: /Immediately after \*\*every\*\* `\.mmd` edit[^\n]*\n\n```bash\nmmx render diagram\.mmd --by agent --note "([^"]*)" --print-if-changed\n```/,
		replace:
			'Immediately after **every** `.mmd` edit you want the human to see, call:\n\n```\nmmx_render({path: "diagram.mmd", note: "$1"})\n```\n\nEdits made with pi\'s `edit` and `write` tools are validated automatically, and an edit you did not send is sent at the end of the run with an automatic note; your own note is better, so call `mmx_render` once the edit is done (several edits in one run can share one note). Edits to a tracked diagram made through `bash` or another tool are noticed after that tool call and treated the same way; an untracked diagram edited that way needs `mmx_render`.',
		required: true,
	},
	{
		name: "--note flag -> note parameter",
		pattern: /`--note`/g,
		replace: "`note`",
		required: true,
	},
	{
		name: "mmx note command -> mmx_note",
		pattern: /To reply without editing, use:\n\n```bash\nmmx note diagram\.mmd "([^"]*)"\n```/,
		replace: 'To reply without editing, use:\n\n```\nmmx_note({path: "diagram.mmd", text: "$1"})\n```',
		required: true,
	},
	{
		name: "mmx note exit codes",
		pattern: /`mmx note` always makes a turn \(`--by` defaults to `agent`\); unrendered edits in the file become part of it\. Exit codes match `mmx render`; it prints nothing on success\./,
		replace:
			"`mmx_note` always makes a turn, as the agent; unrendered edits in the file become part of it. A parse error is reported like `mmx_render`'s, with line and column.",
		required: true,
	},
	{
		name: "waiting: mmx_wait instead of the shell loop",
		pattern: /After your turn, wait for the human's reply instead of polling by hand:[\s\S]*?(?=\n"Unanswered" means)/,
		replace:
			'In pi you rarely wait yourself: when the human presses Send in the cockpit, the extension delivers the turn as an `mmx-turn` message and starts a run (at most three automatic runs in a row; after that the turn waits for the next prompt). To block for a reply inside a run, call:\n\n```\nmmx_wait({path: "diagram.mmd", timeoutSeconds: 300})\n```\n\n- It returns one compact diff JSON line per human turn you have not answered yet (oldest first, same format as diff.json). Respond by editing the diagram and calling `mmx_render({path, note})`, or reply without editing via `mmx_note({path, text})`.\n- `no human turn yet` means the timeout passed. Call it again, or stop. `timeoutSeconds: 0` does not block; it may take up to about half a second to settle and render a direct file edit that is still being written.\n- It refuses while you have an unsent `.mmd` edit; call `mmx_render` first.\n',
		required: true,
	},
	{
		name: "note-only question -> mmx_note",
		pattern: /answer with `mmx note`\)/,
		replace: "answer with `mmx_note`)",
		required: true,
	},
	{
		name: "drop the claude.ai artifact paragraph, keep visual editing via /mmx open",
		pattern: /If the human should EDIT the diagram visually, embed the repo's[\s\S]*?before reading it\./,
		replace:
			"If the human should EDIT the diagram visually, suggest `/mmx open <path>`: it starts the local mmx cockpit for that diagram and opens it in the browser. The human's Send arrives as an `mmx-turn` message.",
		required: true,
	},
	{
		name: "recovery turn: what mmx_render reports",
		pattern: /This recovery turn prints nothing with `--print-if-changed`;/,
		replace: "`mmx_render` reports this recovery turn as `baseline recorded`;",
		required: true,
	},
	{
		name: "error recovery: how pi reports exit codes",
		pattern: /^(## Recover errors\n\n)/m,
		replace:
			"$1In pi, `mmx_render` and `mmx_note` report exit 2 as a tool error with the kind, message, line, and column. The exit codes below are those of the `mmx` CLI underneath.\n\n",
		required: true,
	},
];

const CODEMAP_RULES = [
	{
		name: "frontmatter description",
		pattern: /^description: "(.*)"$/m,
		replace: 'description: "$1 In pi, render with mmx_render and open the cockpit with /mmx open."',
		required: true,
	},
	{
		name: "in-pi block after the title",
		pattern: /^(# A code conversation as one picture\n)/m,
		replace: `$1\n${CODEMAP_IN_PI}`,
		required: true,
	},
	{
		name: "render command -> mmx_render",
		pattern: /`mmx render (\S+) --by agent --note "([^"]*)"`/,
		replace: (_match, path, note) => `\`mmx_render({path: "${path}", note: "${note}"})\``,
		required: true,
	},
	{
		name: "human turn source",
		pattern: /\(diff v2 from `mmx wait`\)/,
		replace: "(diff v2 from an `mmx-turn` message or `mmx_wait`)",
		required: true,
	},
	{
		name: "note-only answer -> mmx_note",
		pattern: /Answer with `mmx note`/,
		replace: "Answer with `mmx_note`",
		required: true,
	},
	{
		name: "repository paths -> skill-relative paths",
		pattern: /adapters\/codemap\//g,
		replace: "<skill-dir>/",
		required: true,
	},
];

export const SKILLS = [
	{
		dir: "mmx",
		source: "skills/mmx/SKILL.md",
		rules: MMX_RULES,
		dropHeadings: [],
		copies: [["skills/mmx/references/diff-schema.md", "references/diff-schema.md"]],
	},
	{
		dir: "mmx-codemap",
		source: "adapters/codemap/SKILL.md",
		rules: CODEMAP_RULES,
		dropHeadings: [],
		copies: [
			["adapters/codemap/codemap.py", "codemap.py"],
			["adapters/codemap/example/index_rust.py", "example/index_rust.py"],
			["adapters/codemap/example/mmx-self/turn-log-change.mmd", "example/mmx-self/turn-log-change.mmd"],
			["adapters/codemap/example/mmx-self/turn-log-change.ko.mmd", "example/mmx-self/turn-log-change.ko.mmd"],
		],
	},
];

export function headings(text) {
	return text.split("\n").filter((line) => /^##+ /.test(line)).map((line) => line.trim());
}

function countMatches(pattern, text) {
	const flags = pattern.flags.includes("g") ? pattern.flags : `${pattern.flags}g`;
	return [...text.matchAll(new RegExp(pattern.source, flags))].length;
}

export function deriveSkill(skill, canonical) {
	let text = canonical;
	for (const rule of skill.rules) {
		const matches = countMatches(rule.pattern, text);
		if (rule.required && matches === 0) {
			throw new Error(`${skill.source}: required rule "${rule.name}" matched nothing; update scripts/derive-skills.mjs`);
		}
		text = text.replace(rule.pattern, rule.replace);
	}
	const end = text.indexOf("\n---\n", 4);
	if (!text.startsWith("---\n") || end < 0) throw new Error(`${skill.source}: missing frontmatter`);
	text = `${text.slice(0, end + 5)}\n${GENERATED(skill.source)}\n${text.slice(end + 5)}`;
	for (const forbidden of FORBIDDEN) {
		if (forbidden.pattern.test(text)) throw new Error(`${skill.source}: derived text still contains ${forbidden.name}`);
	}
	const derivedHeadings = new Set(headings(text));
	for (const heading of headings(canonical)) {
		if (!derivedHeadings.has(heading) && !skill.dropHeadings.includes(heading)) {
			throw new Error(`${skill.source}: heading "${heading}" is missing from the derivation and not in dropHeadings`);
		}
	}
	return text;
}

export async function expectedFiles() {
	const files = new Map();
	for (const skill of SKILLS) {
		const canonical = await fs.readFile(join(repoRoot, skill.source), "utf8");
		files.set(join(skill.dir, "SKILL.md"), Buffer.from(deriveSkill(skill, canonical), "utf8"));
		for (const [from, to] of skill.copies) files.set(join(skill.dir, to), await fs.readFile(join(repoRoot, from)));
	}
	return files;
}

async function listFiles(root) {
	if (!existsSync(root)) return [];
	const out = [];
	for (const entry of await fs.readdir(root, { withFileTypes: true, recursive: true })) {
		if (entry.isFile()) out.push(relative(root, join(entry.parentPath ?? entry.path, entry.name)));
	}
	return out;
}

async function main() {
	const check = process.argv.includes("--check");
	const expected = await expectedFiles();
	const present = await listFiles(skillsRoot);
	const differing = [];
	for (const [path, bytes] of expected) {
		let current;
		try {
			current = await fs.readFile(join(skillsRoot, path));
		} catch {
			current = undefined;
		}
		if (!current || !current.equals(bytes)) differing.push(path);
	}
	const extra = present.filter((path) => !expected.has(path));
	if (check) {
		if (differing.length || extra.length) {
			for (const path of differing) console.error(`differs: skills${sep}${path}`);
			for (const path of extra) console.error(`not derived: skills${sep}${path}`);
			console.error("Run `npm run derive-skills` in adapters/pi.");
			process.exit(1);
		}
		console.log(`skills are up to date (${expected.size} files)`);
		return;
	}
	for (const path of extra) await fs.rm(join(skillsRoot, path));
	for (const [path, bytes] of expected) {
		await fs.mkdir(dirname(join(skillsRoot, path)), { recursive: true });
		await fs.writeFile(join(skillsRoot, path), bytes);
	}
	// Remove directories left empty by deleted files.
	for (const entry of (await fs.readdir(skillsRoot, { withFileTypes: true, recursive: true })).reverse()) {
		if (!entry.isDirectory()) continue;
		const path = join(entry.parentPath ?? entry.path, entry.name);
		if (!(await fs.readdir(path)).length) await fs.rmdir(path);
	}
	console.log(`wrote ${expected.size} files, removed ${extra.length}`);
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
	main().catch((error) => {
		console.error(error instanceof Error ? error.message : String(error));
		process.exit(1);
	});
}
